channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - intel-openmp=2022.0.1
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1n
  - pip=21.2.4
  - pycodestyle=2.6.0
  - python=3.8.13
  - readline=8.1.2
  - scipy=1.6.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.2
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
